In [16]:
import numpy as np

In [32]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133]], dtype='float32')

print(type(targets))


<class 'numpy.ndarray'>


In [33]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])


In [34]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.2617,  1.2508,  0.2421],
        [ 0.0226, -1.1233, -0.2252]], requires_grad=True)
tensor([ 0.6083, -0.9867], requires_grad=True)


above cell gives requires_grad=True allows to get gradient of weights and biases

In [35]:
def model(x):
    return x @ w.t() + b

In [37]:
preds = model(inputs)
print(preds)

tensor([[  75.7118,  -84.2835],
        [ 102.3500, -112.1955],
        [ 159.4801, -162.6059]], grad_fn=<AddBackward0>)


In [38]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [39]:
loss = mse(preds, targets)
print(loss)

tensor(26520.2598, grad_fn=<DivBackward0>)


In [40]:
loss.backward()

In [41]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.2617,  1.2508,  0.2421],
        [ 0.0226, -1.1233, -0.2252]], requires_grad=True)
tensor([[  2301.1929,   2874.6072,   1520.6174],
        [-18793.7324, -22903.1289, -12474.6143]])


In [42]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [43]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(26520.2598, grad_fn=<DivBackward0>)


In [44]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [45]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  71.4518,  -49.8527],
        [  96.7528,  -66.9525],
        [ 152.7438, -108.3276]], grad_fn=<AddBackward0>)


In [46]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(17072.8809, grad_fn=<DivBackward0>)


In [48]:
#  Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  1832.4001,   2314.3972,   1209.9164],
        [-15009.4766, -18382.6172,  -9966.5430]])
tensor([  21.6495, -176.3776])


In [49]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [50]:
print(w)
print(b)

tensor([[-3.0307e-01,  1.1989e+00,  2.1475e-01],
        [ 3.6059e-01, -7.1043e-01, -7.7961e-04]], requires_grad=True)
tensor([ 0.6078, -0.9827], requires_grad=True)


In [51]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(11015.7334, grad_fn=<DivBackward0>)


In [56]:
# Train for 100 epochs
for i in range(100):
    print("Epoch {} started".format(i))
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print("weight={}, bias={}".format(w, b))

Epoch 0 started
weight=tensor([[-0.2776,  0.9783,  0.2465],
        [ 0.5721,  0.4720,  0.1904]], requires_grad=True), bias=tensor([ 0.6079, -0.9820], requires_grad=True)
Epoch 1 started
weight=tensor([[-0.2774,  0.9780,  0.2467],
        [ 0.5713,  0.4729,  0.1900]], requires_grad=True), bias=tensor([ 0.6079, -0.9820], requires_grad=True)
Epoch 2 started
weight=tensor([[-0.2772,  0.9778,  0.2469],
        [ 0.5704,  0.4739,  0.1896]], requires_grad=True), bias=tensor([ 0.6079, -0.9820], requires_grad=True)
Epoch 3 started
weight=tensor([[-0.2770,  0.9775,  0.2470],
        [ 0.5696,  0.4748,  0.1892]], requires_grad=True), bias=tensor([ 0.6079, -0.9821], requires_grad=True)
Epoch 4 started
weight=tensor([[-0.2768,  0.9772,  0.2472],
        [ 0.5687,  0.4758,  0.1888]], requires_grad=True), bias=tensor([ 0.6079, -0.9821], requires_grad=True)
Epoch 5 started
weight=tensor([[-0.2766,  0.9770,  0.2474],
        [ 0.5679,  0.4767,  0.1884]], requires_grad=True), bias=tensor([ 0.6079, -0.9

In [53]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(114.7581, grad_fn=<DivBackward0>)


In [57]:
preds

tensor([[ 56.8735,  79.1448],
        [ 77.7583, 103.0032],
        [121.1530, 125.5115]], grad_fn=<AddBackward0>)

In [58]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])

In [59]:
import torch.nn as nn

In [60]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [61]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [13]:
import torch
from torch.utils.data import TensorDataset

In [63]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [64]:
from torch.utils.data import DataLoader

In [65]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [66]:
for xb, yb in train_dl:
    print(xb)# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [ 73.,  66.,  44.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [118., 132.],
        [102., 120.],
        [ 57.,  69.],
        [ 22.,  37.]])


In [67]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2360, -0.0944, -0.0630],
        [ 0.3189, -0.3533,  0.5441]], requires_grad=True)
Parameter containing:
tensor([-0.4491, -0.4298], requires_grad=True)


In [68]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-26.7101,  22.5802],
        [-34.2636,  32.3286],
        [-37.2822,  11.5384],
        [-30.9110,  37.0427],
        [-30.2048,  25.7506],
        [-26.8517,  23.2523],
        [-34.2322,  33.2259],
        [-37.5812,  12.4014],
        [-30.7693,  36.3705],
        [-30.0318,  25.9758],
        [-26.6788,  23.4775],
        [-34.4052,  33.0008],
        [-37.3135,  10.6410],
        [-31.0839,  36.8176],
        [-30.0632,  25.0785]], grad_fn=<AddmmBackward0>)

In [69]:
# Import nn.functional
import torch.nn.functional as F

In [70]:
loss_fn = F.mse_loss

In [71]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9518.3145, grad_fn=<MseLossBackward0>)


In [72]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [73]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [74]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 263.3543
Epoch [20/100], Loss: 114.6906
Epoch [30/100], Loss: 52.5258
Epoch [40/100], Loss: 145.3907
Epoch [50/100], Loss: 110.6447
Epoch [60/100], Loss: 115.1226
Epoch [70/100], Loss: 78.3521
Epoch [80/100], Loss: 60.4981
Epoch [90/100], Loss: 26.7787
Epoch [100/100], Loss: 16.7338


In [75]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.0436,  71.7946],
        [ 80.8576, 101.5963],
        [119.3948, 128.5651],
        [ 27.1825,  45.9803],
        [ 95.9937, 115.4248],
        [ 56.9184,  70.9638],
        [ 80.4170, 101.7688],
        [119.5730, 129.2779],
        [ 28.3077,  46.8111],
        [ 96.6784, 116.4281],
        [ 57.6030,  71.9671],
        [ 79.7323, 100.7655],
        [119.8354, 128.3926],
        [ 26.4978,  44.9770],
        [ 97.1190, 116.2556]], grad_fn=<AddmmBackward0>)

In [76]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])