# **Tensors! what are that?**

The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serialization of Tensors and arbitrary types, and other useful utilities.

- is_tensor
- numel
- asarray
- as_tensor
- arange

Before we begin, let's install and import PyTorch

**_is_tensor()_**

For the provided object to the function is_tensor() it returns boolean value True if it is a PyTorch tensor.

In [3]:
import numpy as np
import torch as t

In [ ]:
arr = np.array([[22, 45, 78],
               [23, 25, 15],
               [78, 96, 65]], dtype='float32')

In [ ]:
ten = t.from_numpy(arr)
print(type(ten))

<class 'torch.Tensor'>


Using is_tensor method to check if given object is torch tensor.

In [ ]:
print(t.is_tensor(arr))

False


In [ ]:
print(t.is_tensor(ten))

True


**_numel()_**

Returns the total number of elements in the input tensor.

In [ ]:
print(t.numel(ten))

9


**_asarray()_**

This method converts the the given object to the Tensor.

In [ ]:
type(arr)

numpy.ndarray

NumPy array conversion to the torch tensor.







In [ ]:
array = t.asarray(arr)
print(type(array))

<class 'torch.Tensor'>


**_as_tensor()_**

Converts data into a tensor, sharing data and preserving autograd history if possible.

In [ ]:
newT = t.as_tensor(data=[45, 15, 78, 36])
newT

tensor([45, 15, 78, 36])

**_arange()_**

Returns a 1-D tensor of size
[
end
−
start/
step]
[
step
end−start
​]
# with values from the interval [start, end] taken with common difference step beginning from start.

 Parameters


**start (Number)** -  the starting value for the set of points. Default: 0.

**end (Number)**   -  the ending value for the set of points

**step (Number)** - the gap between each pair of adjacent points. Default: 1.

In [6]:
t.arange(5)

tensor([0, 1, 2, 3, 4])

In [7]:
t.arange(15, 60, 8)

tensor([15, 23, 31, 39, 47, 55])

In [10]:
t.arange(20, 10)

RuntimeError: upper bound and larger bound inconsistent with step sign

That is why the start value should be lessor than the end value.